### ISSUE TITLE
Mogelijkheid om een tooltip mee tegeven

### ISSUE THREAD

**Issue by ao-jhelmich** [mach3builders/ui-laravel#1]
<img width="240" alt="schermafbeelding 2018-08-31 om 17 34 56" src="https://user-images.githubusercontent.com/17061364/44921949-41e97380-ad44-11e8-8583-ebe56a525f70.png">

**Comment by robbinbenard** [comment]
Toegevoegd in https://github.com/mach3builders/ui-laravel/commit/4dacdd3f5ea7cead8f7bc21431c0326f4412c7d5
